version: '2'

services:

        mosquitto:
                build: .
                volumes:
                - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
                ports:
                - "1883:1883"
                - "8883:8883"
                environment:
                - PORT=8080
                labels:
                - "local.example.description=Mosquitto v1.6.9 MQTT server"

